services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/booking
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:1234567@db:5432/demo
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_DB=demo
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: